/**
 * Static fallback copy of the PII Engine action registry.
 *
 * Used when the live ``GET /actions`` endpoint is unreachable so the
 * reference block still renders. The PII Engine registry is the source of
 * truth — keep this in sync when actions change there.
 */

import type { ActionDef } from "@/lib/api/policy-engine";

export const FALLBACK_ACTIONS: ActionDef[] = [
  {
    name: "pass",
    decision: "pass",
    reversible: false,
    severity: "pass",
    strictness: 1,
    params: [],
    exampleInput: "My name is John Doe.",
    exampleOutput: "My name is John Doe.",
    validation: [],
    notes: "Entity passes through unmodified.",
  },
  {
    name: "block",
    decision: "block",
    reversible: false,
    severity: "fail",
    strictness: 9,
    params: [],
    exampleInput: "My name is John Doe.",
    exampleOutput: "(request rejected — HTTP 403, LLM never called)",
    validation: [],
    notes: "Reject the request before an LLM is called.",
  },
  {
    name: "mask",
    decision: "apply_actions",
    reversible: false,
    severity: "info",
    strictness: 2,
    params: [
      {
        name: "masking_char",
        type: "string",
        default: "*",
        description: "Mask character",
        options: [],
      },
      {
        name: "chars_to_mask",
        type: "int",
        default: "100",
        description: "Maximum characters to mask",
        options: [],
      },
      {
        name: "from_end",
        type: "bool",
        default: "true",
        description: "Mask from the end of the value",
        options: [],
      },
    ],
    exampleInput: "My name is John Doe.",
    exampleOutput: "My name is ********.",
    validation: [],
    notes: "Replace characters while preserving length.",
  },
  {
    name: "replace",
    decision: "apply_actions",
    reversible: false,
    severity: "info",
    strictness: 6,
    params: [
      {
        name: "new_value",
        type: "string",
        default: "<ENTITY>",
        description: "Replacement text",
        options: [],
      },
    ],
    exampleInput: "My name is John Doe.",
    exampleOutput: "My name is <PERSON>.",
    validation: [],
    notes: "Replace with a configured value; <ENTITY> expands to the normalized type.",
  },
  {
    name: "redact",
    decision: "apply_actions",
    reversible: false,
    severity: "info",
    strictness: 7,
    params: [],
    exampleInput: "My name is John Doe.",
    exampleOutput: "My name is .",
    validation: [],
    notes: "Remove the detected value.",
  },
  {
    name: "hash",
    decision: "apply_actions",
    reversible: false,
    severity: "info",
    strictness: 3,
    params: [
      {
        name: "hash_type",
        type: "enum",
        default: "sha256",
        description: "Keyed hash algorithm",
        options: ["sha256"],
      },
    ],
    exampleInput: "My name is John Doe.",
    exampleOutput: "My name is 1f8b9c2a4d7e5f6b0c3a1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a.",
    validation: [],
    notes: "Use a keyed policy-scoped rotating-window HMAC-SHA-256 value.",
  },
  {
    name: "encrypt",
    decision: "apply_actions",
    reversible: true,
    severity: "info",
    strictness: 4,
    params: [],
    exampleInput: "My name is John Doe.",
    exampleOutput: "My name is <ENCRYPTED_PERSON_0123456789abcdef_fedcba9876543210>.",
    validation: [],
    notes: "Encrypt and reverse through a trusted map.",
  },
  {
    name: "reversible_replace",
    decision: "apply_actions",
    reversible: true,
    severity: "info",
    strictness: 5,
    params: [],
    exampleInput: "My name is John Doe.",
    exampleOutput: "My name is <REV_PERSON_0123456789abcdef_fedcba9876543210>.",
    validation: [],
    notes: "Use a reversible entity token.",
  },
  {
    name: "reroute",
    decision: "reroute",
    reversible: false,
    severity: "warn",
    strictness: 8,
    params: [],
    exampleInput: "My name is John Doe.",
    exampleOutput: "My name is ********.  (request routed to the local model)",
    validation: [],
    notes: "Route the request to a trusted local target.",
  },
];
